import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, TextField } from '@mui/material'
import { createTheme } from '@mui/material/styles'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Crud Liam Bialy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        
        <h1>
            Crud on React
        </h1>
        <TextField id="standard-basic" label="Nombre" variant="standard" />
        <TextField id="standard-basic" label="Apellido" variant="standard" />
        <Button variant="contained" color="success">Add</Button>

        
      </main>
    </>
  )
}
